# Fase 1: compilazione Angular 
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Fase 2: immagine finale, servita da Nginx
FROM nginx:alpine
COPY --from=build /app/dist/museo-villaserena-frontend/browser /usr/share/nginx/html
EXPOSE 80