spring.application.name=museo-backend
server.port=${BACKEND_PORT:8080}

# Database Configuration, se non c'è la variabile Docker, usa i valori locali dopo i :
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:museo_villaserena}?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_ROOT_PASSWORD:!MuseoVillaSerena@2026}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Security Configuration
jwt.secret=${JWT_SECRET:changeThisSecretKeyInProductionEnvironment}
jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html

# Upload File / Immagini
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Cifratura e Sicurezza
sicurezza.chiave-cifratura=${ENCRYPTION_KEY:ChiaveDiSviluppoLocaleNonUsareInProd}

# Integrazione PayPal (Sandbox)
paypal.client-id=${PAYPAL_CLIENT_ID:BAAlcTa91MkQcyjKUeknm8fWN2ZGkdzPJ2Izus_HxkWMSTfZF3NBK8yz2nQfULpDoB_d6lST6GcoP_hGfY}
paypal.client-secret=${PAYPAL_CLIENT_SECRET:EBHLRnAg9tIlFnMVwL7WRf_y_YXemWsM15sKGKgwvs94JZ6grz01nxbCfX57vZ7ly3k3uzsCiMdwPFC5}
paypal.base-url=https://api-m.sandbox.paypal.com